config-version: 2

name: "minimal_repro"
version: '1.0.0'
config-version: 2

profile: minimal-repro # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "build_env": "junk"
  "org_prefix": "junk"

seeds:
  minimal_repro:
    +schema: transient

models:
  +materialized: table
  minimal_repro:
    intermediate:
      +schema: transient
    reporting:
      +database: reporting
      +schema: reporting
