config-version: 2

name: "minimal_repro"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

profile: minimal_repro # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "build_env": "dev"
  "org_prefix": "123"

seeds:
  minimal_repro:
    +schema: raw
    +database: "test_db"

models:
  minimal_repro:
    +database: "test_db"
    +schema: models
    +materialized: table